name: Mention To Slack On Auto Assign
on:
  workflow_run:
    workflows:
      - Auto Assign
    types:
      - completed
jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          bot-name: "actions-mention-to-slack(lambda)"
          run-id: ${{ github.run_id }}
